name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploying Prophecy Streamlit
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.IP_SERVER }}
        username: ${{ secrets.USERNAME_SERVER }}
        key: ${{ secrets.KEY_SERVER }}
        port: 22
        script: |
          cd ${{ secrets.PATH_APP_SERVER }}
          git pull origin main
          docker compose down
          docker rmi prophecy-streamlit:latest
          docker builder prune -f
          docker compose up -d
